services:
  mysql:
    container_name: 'mysql'
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=home_connect'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'